name: deploy react app
on: push
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: get source from repo
        uses: actions/checkout@v3
      - name: Install dependensis
        run: npm ci
      - name: test
        run: npm run test
      - name: check es lint
        run: npm run lint
      - name: Delply
        run: echo Deploying...
