name: deploy react app
on:
  push:
    branches:
      - master
      #path-ignore:
      #'.github/workflows/*'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: get source from repo
        uses: actions/checkout@v3
      - name: cash dependysis
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependensis
        run: npm ci
      - name: test
        run: npm run test
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: get source from repo
        uses: actions/checkout@v3
      - name: cash dependysis
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependensis
        run: npm ci
      - name: check es lint
        run: npm run lint
  build:
    needs: [test, lint]
    strategy:
      matrix:
        node-version: [14, 16]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: get source from repo
        uses: actions/checkout@v3
      - name: install node js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: cash dependysis
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependensis
        run: npm ci
      - name: build project
        run: npm run build
      - name: Delply
        run: echo Deploying...
