name: Build
on:
  [push, workflow_dispatch]
jobs:
  build:
        runs-on: ubuntu-latest
        steps:
         - name: get code
           uses: actions/checkout@v3
         - name: install
           run: npm ci
         - name: build project
           run: npm run build
         - name: upload artifact
           uses: actions/upload-artifact@v3
           with:
              name: build-files
              path: build
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get build
        uses: actions/download-artifact@v3
        with:
          name: build-files
