name: Test react app
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: get source from repo
      - uses: actions/checkout@v3
      - name: Install dependensis
      - uses: npm install
        run: npm ci
      - name: test
        run: npm run test
